### ISSUE TITLE
Problem maya 2023 and win 11

### ISSUE THREAD

**Issue by hristo-kolev** [JustinPedersen/maya_fspy#16]
Hi, I'm trying to load the script by follawing the instruction but give me error (No module named 'pymel'), after research, I found this solution https://forums.autodesk.com/t5/maya-programming/maya-2022-pymel-how-to-import/td-p/10409310
But after that every time when I try to load the script (import maya_fspy.ui as mfspy_ui
mfspy_ui.maya_fspy_ui()) give me other error (Error: OSError: file C:\Users\hrist\AppData\Roaming\Python\Python39\site-packages\pymel\internal\parsers.py line 790: Cannot find maya documentation. Expected to find it at C:\Program Files\Autodesk\Maya2023\docs\Maya2023\en_US)
Any idea how to solve this?
Thanks in advanced.

**Comment by JustinPedersen** [comment]
Hey @hristo-kolev  

That seems to be an internal issue with PyMel in Maya 2023 and is something completely out of my control. 

You might have a better chance at trying in an earlier version of Maya, I know it's been tested on 2018 -> 2022. Alternatively you could try the v2 branch where I have completely re-written the tool and removed PyMel entirely because its been such a hassle for so many users.  

[V2 branch](https://github.com/JustinPedersen/maya_fspy/tree/v2.0.0)

This is still a work in progress and will likely have bugs and issues though.

**Comment by hristo-kolev** [comment]
Hi, thansk for the help. It works with maya 2023. Thank you for the help. Have a nice day.
________________________________
От: Justin Pedersen ***@***.***>
Изпратено: 30 септември 2022 г. 12:32
До: JustinPedersen/maya_fspy ***@***.***>
Як: hristo-kolev ***@***.***>; Mention ***@***.***>
Тема: Re: [JustinPedersen/maya_fspy] Problem maya 2023 and win 11 (Issue #16)


Hey @hristo-kolev<https://github.com/hristo-kolev>

That seems to be an internal issue with PyMel in Maya 2023 and is something completely out of my control.

You might have a better chance at trying in an earlier version of Maya, I know it's been tested on 2018 -> 2022. Alternatively you could try the v2 branch where I have completely re-written the tool and removed PyMel entirely because its been such a hassle for so many users.

V2 branch<https://github.com/JustinPedersen/maya_fspy/tree/v2.0.0>

This is still a work in progress and will likely have bugs and issues though.
